openapi: 3.1.0
info:
  title: Carton Caps Referral Service API
  version: 1.0.0
  description: API for generating shareable referral links and handling the 'deferred' 
    attribution process to customize onboarding for new users after app install.
paths:
  /referrals/new-link:
    get:
      parameters:
        - name: campaign
          in: query
          required: false # It's optional; we can have a default
          description: "The marketing channel or source (e.g., twitter, whatsapp)."
          schema:
            type: string
            maxLength: 50
            example: "whatsapp_promo"
      summary: Generate a shareable deep link
      description: >
        Creates a unique referral link that can be shared by existing users to invite new users.
        it connects to third-party vendor for deferred deep link support.
      operationId: CreateReferralLink
      responses:
        '201':
          description: Creates new referal link
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/ReferralLink'
        '401':
          description: Unauthorized - User must be logged in to refer others.
  /referrals/attribute:
    post:
      summary: match a new installation to the referral code
      description: >
        It "pairs" the device fingerprint with a referral code found in the deep link.
      operationId: MatchDeviceToReferral
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AttributionRequest'
      responses:
        '200':
          description: Device successfully attributed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OnboardingMetadata'
        '404':
          description: Referral code is invalid or expired.
  /referrals/claim:
    post:
      summary: Finalize the referral and issue rewards
      description: >
        Called after the new user successfully completes registration and uses auth token. 
        Moves the status from 'Pending' to 'Claimed'.
      operationId: ClaimReferral
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                attributionToken:
                  type: string
      responses:
        '200':
          description: Reward processed.
        '409':
          description: Conflict - User has already claimed a referral or is not a new user.
  /referrals/my-referrals:
    get:
      summary: Get a list of users I have referred and their current status
      operationId: GetMyReferrals
      parameters:
        - name: status
          in: query
          description: Filter by status (e.g., pending, completed)
          schema:
            type: string
            enum: [pending, completed, rewarded]
      responses:
        '200':
          description: A list of referrals associated with the authenticated user
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ReferralStatusResponse'
components:
  schemas:
    ReferralLink:
      type: object
      properties:
        referralCode:
          type: string
          example: "FRIEND2026"
        shortUrl:
          type: string
          format: uri
          example: "https://myapp.link/FRIEND2026"
        expiryDate:
          type: string
          format: date-time

    AttributionRequest:
      type: object
      required: [referralCode, deviceId]
      properties:
        referralCode:
          type: string
          example: "FRIEND2026"
        deviceId:
          type: string
          description: "Unique hardware ID or IDFV/GAID to identify the install."
        os:
          type: string
          enum: [ios, android]

    OnboardingMetadata:
      type: object
      properties:
        referrerName:
          type: string
          example: "Alex"
        rewardAmount:
          type: number
          example: 10.00
        attributionToken: 
          type: string
          description: "Pass this to /claim after signup."

    ReferralStatusResponse:
      type: object
      properties:
        inviteeName:
          type: string
          example: "John D."
          description: "Name of the person referred"
        status:
          type: string
          enum: [pending, completed, rewarded]
          example: "completed"
        dateJoined:
          type: string
          format: date
          example: "2026-01-25"